### ISSUE TITLE
How i can restart application and continue import/export work

### ISSUE THREAD

**Issue by kurenchuksergey** [Paracells/natlex#5]
https://github.com/Paracells/natlex/blob/d550474ed5a9193849d0a54dcf54e38856b6a45c/src/main/java/ru/paracells/natlex/controllers/XlsxController.java#L28

**Comment by Paracells** [comment]
Move it to another layer and now it not depend on "controller" layer and save it DB
https://github.com/Paracells/natlex/blob/54fb308be0b521b8807727654cc635b69ea1ccdd/src/main/java/ru/paracells/natlex/service/JobServiceImpl.java#L20
