### ISSUE TITLE
why async and why you return CompletableFuture?

### ISSUE THREAD

**Issue by kurenchuksergey** [Paracells/natlex#6]
https://github.com/Paracells/natlex/blob/d550474ed5a9193849d0a54dcf54e38856b6a45c/src/main/java/ru/paracells/natlex/controllers/XlsxController.java#L93

**Comment by Paracells** [comment]
hope it got better https://github.com/Paracells/natlex/blob/54fb308be0b521b8807727654cc635b69ea1ccdd/src/main/java/ru/paracells/natlex/controllers/XlsxController.java#L69
