### ISSUE TITLE
Result and current State should be in DB

### ISSUE THREAD

**Issue by kurenchuksergey** [Paracells/natlex#8]
https://github.com/Paracells/natlex/blob/d550474ed5a9193849d0a54dcf54e38856b6a45c/src/main/java/ru/paracells/natlex/controllers/XlsxController.java#L27

**Comment by Paracells** [comment]
Create a new DB Job and save ID and State of current work https://github.com/Paracells/natlex/blob/54fb308be0b521b8807727654cc635b69ea1ccdd/src/main/java/ru/paracells/natlex/service/SaveAndReadServiceImpl.java#L65
